name: ci
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'

jobs:
  
  build-container:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Chekcout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push to docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: venkatvinay1/helloworldapp:1.0.${{ github.run_number}}



